


server:
  port: 8080


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
      username: root
      password: hsp


#  web:
#    resources:
#      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

#    日期格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #别名
  type-aliases-package: com.system.archives.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

#日志
logging:
  level:
    root: info
#  file:
#    name:
#    path:
